import React, { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";

const QrTripPage = () => {
  const [tripText, setTripText] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // Extract ID from URL manually
  const path = window.location.pathname;
  const qrTripId = path.split("/qr-trip/")[1];

  useEffect(() => {
    if (!qrTripId) {
      setError("Invalid QR link");
      setLoading(false);
      return;
    }

    const fetchTrip = async () => {
      try {
        const res = await fetch(
          `http://localhost:5001/api/qr-trips/${qrTripId}`
        );

        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.message || "Trip not found");
        }

        setTripText(data.text);
      } catch (err) {
        setError("Unable to load itinerary.");
      } finally {
        setLoading(false);
      }
    };

    fetchTrip();
  }, [qrTripId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-600">Loading itinerary…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-red-500">{error}</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-lg p-6">

        <h1 className="text-2xl font-semibold text-gray-800 mb-4">
          Your Travel Itinerary
        </h1>

        <div className="prose max-w-none">
          <ReactMarkdown>
            {tripText}
          </ReactMarkdown>
        </div>

        <div className="mt-6 text-xs text-gray-400 text-center">
          ✨ Generated by AI • Shared via QR
        </div>

      </div>
    </div>
  );
};

export default QrTripPage;
