import React, { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";

/* =========================
   Helpers
========================= */

// Extract destination(s) from itinerary text
const extractLocation = (text = "") => {
  const match =
    text.match(/Destinations?:\s*(.+)/i) ||
    text.match(/Destination:\s*(.+)/i);

  return match ? match[1].trim() : null;
};

const QrTripPage = () => {
  const [tripText, setTripText] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // Extract QR ID from URL
  const path = window.location.pathname;
  const qrTripId = path.split("/qr-trip/")[1];

  /* =========================
     Fetch itinerary
  ========================= */
  useEffect(() => {
    if (!qrTripId) {
      setError("Invalid QR link");
      setLoading(false);
      return;
    }

    const fetchTrip = async () => {
      try {
        const res = await fetch(
          `https://projectx-yzu3.onrender.com/api/qr-trips/${qrTripId}`
        );

        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.message || "Trip not found");
        }

        setTripText(data.text);
      } catch {
        setError("Unable to load itinerary.");
      } finally {
        setLoading(false);
      }
    };

    fetchTrip();
  }, [qrTripId]);

  /* =========================
     PDF Download
  ========================= */
  const handleDownloadPDF = () => {
    window.print(); // browser-native, reliable
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-600">Loading itinerary…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-red-500">{error}</p>
      </div>
    );
  }

  const location = extractLocation(tripText);

  return (
    <div className="min-h-screen bg-[#f6f7f9] text-gray-800">

      {/* ================= HEADER ================= */}
      <header className="sticky top-0 z-10 bg-white border-b print:hidden">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">



          {/* ACTION */}

        </div>
      </header>

      {/* ================= CONTENT ================= */}
      <main className="max-w-5xl mx-auto px-6 py-10 bg-white print:px-0 print:py-0">
        {/* ===== PROJECT X COMBINED LOGO ===== */}
        <div className="flex justify-center items-center gap-2 mb-10">
          <span className="text-3xl md:text-4xl font-bold text-gray-800 tracking-wide">
            EXPEDITIO
          </span>

          <img
            src="/logo.png"
            alt="X"
            className="h-10 md:h-12"
          />
        </div>


        {/* TITLE */}
        <div className="mb-8">
          <h2 className="text-3xl font-semibold">
            Your Travel Itinerary
          </h2>

          {location && (
            <p className="mt-2 text-gray-600 text-sm">
              📍 {location}
            </p>
          )}
        </div>

        {/* ITINERARY */}
        <article
          className="
            prose prose-slate max-w-none
            prose-headings:font-semibold
            prose-headings:mt-6
            prose-p:leading-relaxed
            prose-li:my-1
          "
        >
          <ReactMarkdown>
            {tripText}
          </ReactMarkdown>
        </article>

        {/* FOOTER */}
        <footer className="mt-14 pt-6 border-t text-center text-xs text-gray-400">
          ✨ Generated by Expeditio AI • Shared via QR
          <br />
          Plan smarter. Travel better.
        </footer>



      </main>

      <button
        onClick={handleDownloadPDF}
        className="rounded-full border px-4 py-2 text-sm 
                       hover:bg-gray-100 transition"
      >
        ⬇ Download PDF
      </button>

    </div>
  );
};

export default QrTripPage;
