import React from "react";

const TripResults = ({ suggestions, loading, onClose }) => {
  /* ===== LOADING STATE ===== */
  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="bg-white rounded-3xl shadow-xl px-10 py-12 text-center space-y-4">
          <div className="w-12 h-12 border-4 border-[#5b7c67]/30 border-t-[#5b7c67]
                          rounded-full animate-spin mx-auto" />
          <p className="text-lg font-medium text-gray-700">
            ✨ Planning your trip with AI…
          </p>
          <p className="text-sm text-gray-500">
            Please wait a few seconds
          </p>
        </div>
      </div>
    );
  }

  /* ===== NO DATA ===== */
  if (!suggestions?.text) {
    return (
      <div className="text-center text-gray-600 mt-10">
        No itinerary generated.
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto mt-12 space-y-8">

      {/* ===== HEADER ===== */}
      <div className="bg-white rounded-3xl shadow-lg px-8 py-6
                      flex items-center justify-between">
        <h2 className="text-xl md:text-2xl font-semibold text-gray-800">
          Your AI Travel Plan
        </h2>

        <button
          onClick={onClose}
          className="text-2xl text-gray-400 hover:text-gray-700 transition"
          aria-label="Close"
        >
          ×
        </button>
      </div>

      {/* ===== AI OUTPUT ===== */}
      <div className="bg-white rounded-3xl shadow-lg p-8">
        <pre className="bg-slate-50
          border border-slate-200
          rounded-xl
          p-6
          text-slate-700
          text-[15px]
          leading-[1.7]
          font-serif

          whitespace-pre-wrap
          break-words
          overflow-x-auto

          w-full
          max-w-[900px]
          mx-auto">
          {suggestions.text}
        </pre>
      </div>

      {/* ===== ACTION BUTTONS ===== */}
      <div className="bg-white rounded-3xl shadow-lg px-8 py-6
                      flex flex-wrap gap-4 justify-center md:justify-between">

        <button
          className="rounded-full bg-[#5b7c67] px-6 py-3
                     text-white text-sm font-medium
                     hover:bg-[#4a6a58] transition"
        >
          💾 Save
        </button>

        <button
          className="rounded-full border border-gray-300 px-6 py-3
                     text-sm font-medium text-gray-700
                     hover:bg-gray-50 transition"
        >
          📤 Share
        </button>

        <button
          onClick={() => window.print()}
          className="rounded-full border border-gray-300 px-6 py-3
                     text-sm font-medium text-gray-700
                     hover:bg-gray-50 transition"
        >
          🖨️ Print
        </button>
      </div>

      {/* ===== FOOT NOTE ===== */}
      <div className="text-center text-xs text-gray-500">
        ✨ Generated by AI. Times and costs are approximate.
      </div>

    </div>
  );
};

export default TripResults;
