import React from 'react';
import '../styles/TripResults.css';

const TripResults = ({ suggestions, onClose }) => {
  const saveTrip = () => {
    const savedTrips = JSON.parse(localStorage.getItem('userTrips') || '[]');
    savedTrips.push({
      id: Date.now(),
      date: new Date().toLocaleDateString(),
      suggestions: suggestions,
      savedAt: new Date().toISOString()
    });
    localStorage.setItem('userTrips', JSON.stringify(savedTrips));
    alert('Trip saved to your history!');
  };

  const shareTrip = () => {
    const shareText = `My AI-Powered Trip Plan:\n\n` +
      suggestions.map(s => `⏰ ${s.time}\n📍 ${s.activity}\n🚗 ${s.transport}`).join('\n\n');
    
    if (navigator.share) {
      navigator.share({
        title: 'My Travel AI Itinerary',
        text: shareText
      });
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Trip copied to clipboard! 📋');
    }
  };

  return (
    <div className="trip-results">
      <div className="results-header">
        <h2>🎉 Your AI-Powered Itinerary</h2>
        <button className="close-results" onClick={onClose}>×</button>
      </div>

      <div className="results-summary">
        <div className="summary-card">
          <span className="summary-icon">⏱️</span>
          <div>
            <h4>Total Duration</h4>
            <p>{suggestions.length * 3} hours</p>
          </div>
        </div>
        <div className="summary-card">
          <span className="summary-icon">💰</span>
          <div>
            <h4>Estimated Cost</h4>
            <p>₹{suggestions.reduce((sum, s) => sum + (parseInt(s.cost) || 0), 0)}</p>
          </div>
        </div>
        <div className="summary-card">
          <span className="summary-icon">🚗</span>
          <div>
            <h4>Transport</h4>
            <p>Auto/Taxi/Walk</p>
          </div>
        </div>
      </div>

      <div className="timeline">
        {suggestions.map((item, index) => (
          <div key={index} className="timeline-item">
            <div className="timeline-marker">
              <span>{index + 1}</span>
            </div>
            <div className="timeline-content">
              <div className="time-badge">{item.time}</div>
              <h3>{item.activity}</h3>
              <p className="location">📍 {item.location}</p>
              <div className="details">
                <span className="transport">🚗 {item.transport}</span>
                <span className="duration">⏱️ {item.duration}</span>
                <span className="cost">💰 {item.cost}</span>
              </div>
              <p className="description">{item.description}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="action-buttons">
        <button className="save-btn" onClick={saveTrip}>
          💾 Save Trip
        </button>
        <button className="share-btn" onClick={shareTrip}>
          📤 Share
        </button>
        <button className="print-btn" onClick={() => window.print()}>
          🖨️ Print
        </button>
      </div>

      <div className="ai-note">
        <p>✨ Generated by AI based on your preferences. Times are approximate.</p>
      </div>
    </div>
  );
};

export default TripResults;