import React, { useState, useEffect } from "react";

const TripResults = ({ suggestions, loading, onClose }) => {
  const messages = [
    "Understanding your preferences…",
    "Analyzing routes & distances…",
    "Finding food & local spots…",
    "Balancing time and budget…",
    "Finalizing your itinerary…",
  ];

  const [step, setStep] = useState(0);
  const [showTyping, setShowTyping] = useState(false);
  const [typedText, setTypedText] = useState("");

  /* ================= LOADING TEXT ROTATION ================= */
  useEffect(() => {
    if (!loading) return;
    const interval = setInterval(() => {
      setStep((prev) => (prev + 1) % messages.length);
    }, 3000);
    return () => clearInterval(interval);
  }, [loading]);

  /* ================= START TYPING AFTER LOADING ================= */
  useEffect(() => {
    if (loading) {
      setShowTyping(false);
      setTypedText("");
      return;
    }

    if (!suggestions?.text) return;

    // small delay so transition feels smooth
    const delay = setTimeout(() => {
      setShowTyping(true);
    }, 500);

    return () => clearTimeout(delay);
  }, [loading, suggestions]);

  /* ================= TYPING EFFECT ================= */
  useEffect(() => {
    if (!showTyping) return;

    let index = 0;
    const fullText = suggestions.text;

    const typingInterval = setInterval(() => {
      index++;
      setTypedText(fullText.slice(0, index));

      if (index >= fullText.length) {
        clearInterval(typingInterval);
      }
    }, 25); // typing speed

    return () => clearInterval(typingInterval);
  }, [showTyping, suggestions]);

  /* ================= LOADING ================= */
  if (loading) {
    return (
      <div className="min-h-screen pt-24 flex items-center justify-center px-4">
        <div className="bg-white rounded-3xl shadow-xl p-8 text-center space-y-6 max-w-md w-full">

          <div className="w-14 h-14 border-4 border-[#5b7c67]/30
                          border-t-[#5b7c67]
                          rounded-full animate-spin mx-auto" />

          <p className="text-lg font-semibold text-gray-800">
            ✨ Planning your trip
          </p>

          <p className="text-sm text-gray-600">
            {messages[step]}
          </p>

          <p className="text-xs text-gray-400">
            This may take a few seconds…
          </p>

        </div>
      </div>
    );
  }

  /* ================= NO DATA ================= */
  if (!suggestions?.text) {
    return (
      <div className="pt-24 text-center text-gray-600">
        No itinerary generated.
      </div>
    );
  }

  /* ================= RESULT (TEXT ONLY) ================= */
  return (
    <div className="min-h-screen pt-24">
      <div className="max-w-4xl mx-auto px-4 space-y-6">

        {/* Header */}
        <div className="bg-white rounded-3xl shadow-lg p-6 flex justify-between items-center">
          <h2 className="text-xl md:text-2xl font-semibold text-gray-800">
            Your AI Travel Plan
          </h2>
          <button
            onClick={onClose}
            className="text-2xl text-gray-400 hover:text-gray-700"
          >
            ×
          </button>
        </div>

        {/* Typed Text */}
        <div className="bg-white rounded-3xl shadow-lg p-6">
          <pre className="bg-slate-50 border border-slate-200 rounded-xl
                          p-5 text-slate-700 text-[15px]
                          leading-[1.7] font-serif
                          whitespace-pre-wrap break-words
                          min-h-[300px]">
            {typedText}
            <span className="animate-pulse">▍</span>
          </pre>
        </div>

        <div className="text-center text-xs text-gray-500">
          ✨ Generated by AI. Content may vary.
        </div>

      </div>
    </div>
  );
};

export default TripResults;
